{% set version = "0.7.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-marginaleffects
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/marginaleffects_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/marginaleffects/marginaleffects_{{ version }}.tar.gz
  sha256: 223975a8cb3ebd96c6f852b875d2dee62a7d9d60a8704baf7ea915097c9378df

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate
    - r-data.table
    - r-generics
    - r-insight >=0.17.1
  run:
    - r-base
    - r-checkmate
    - r-data.table
    - r-generics
    - r-insight >=0.17.1

test:
  commands:
    - $R -e "library('marginaleffects')"           # [not win]
    - "\"%R%\" -e \"library('marginaleffects')\""  # [win]

about:
  home: https://vincentarelbundock.github.io/marginaleffects/ https://github.com/vincentarelbundock/marginaleffects
  license: GPL-3.0-or-later
  summary: Compute, summarize, and plot marginal effects, adjusted predictions, contrasts, and marginal means for a wide variety of models.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
