{% set version = "0.28.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-marginaleffects
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/marginaleffects_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/marginaleffects/marginaleffects_{{ version }}.tar.gz
  sha256: ccdcfba1db6e3325fcc63592ac0afdf0720b1b09992cafda9f7409c6971611f4

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-formula                  # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-rcppeigen                # [build_platform != target_platform]
    - r-backports                # [build_platform != target_platform]
    - r-checkmate                # [build_platform != target_platform]
    - r-data.table               # [build_platform != target_platform]
    - r-generics                 # [build_platform != target_platform]
    - r-insight                  # [build_platform != target_platform]
    - r-rlang                    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("c") }}            # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-formula
    - r-rcpp >=1.0.0
    - r-rcppeigen
    - r-backports
    - r-checkmate
    - r-data.table >=1.16.4
    - r-generics
    - r-insight >=1.3.0
    - r-rlang
  run:
    - r-base
    - r-formula
    - r-rcpp >=1.0.0
    - r-rcppeigen
    - r-backports
    - r-checkmate
    - r-data.table >=1.16.4
    - r-generics
    - r-insight >=1.3.0
    - r-rlang

test:
  commands:
    - $R -e "library('marginaleffects')"           # [not win]
    - "\"%R%\" -e \"library('marginaleffects')\""  # [win]

about:
  home: https://vincentarelbundock.github.io/marginaleffects/
  dev_url: https://github.com/vincentarelbundock/marginaleffects
  license: GPL-3.0-or-later
  summary: Compute, summarize, and plot marginal effects, adjusted predictions, contrasts, and marginal means for a wide variety of models.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
